service: sls-todo-api

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  stage: dev
  timeout: 10

functions:
  createTweet:
    handler: handler.createTweet
    events:
      - http:
          path: tweet
          method: post
          cors: true
  
  getTweets:
    handler: handler.getTweets
    events:
      - http:
          path: tweets
          method: get
          cors: true

plugins:
  - serverless-offline
